workflows:
  android-workflow:
    name: Android APK Build

    environment:
      vars:
        PACKAGE_NAME: "com.example.app"

    scripts:
      - ./gradlew assembleRelease

    artifacts:
      - app/build/outputs/**/*.apk
